package hu.ogyhivatal.voting.exception;

public enum ErrorCode {

	SZAVAZAS_INVALID_JSON,
	SZAVAZAS_INVALID_STRUCTURE,
	SZAVAZAS_ELNOK_NINCS_SZAVAZAT,
	SZAVAZAS_KEPVISELO_TOBBSZOR_SZAVAZOTT,
	SZAVAZAS_IDOPONT_FOGLALT,
	SZAVAZAS_ID_GENERALASI_HIBA,
	SZAVAZAS_NEM_TALALHATO,
	KEPVISELO_SZAVAZAT_NEM_TALALHATO,
	IDOSZAK_ERVENYTELEN,
	INTERNAL_ERROR
}
